name: terraform-module-jobs
on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Github
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.TERRAFORM_TOKEN}}

      - name: Get repository
        uses: actions/checkout@v3.5.2

      - name: Generate Terraform Docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: automated-docs
